name: shellnotes
base: core18
version: '3.0'
summary: An easy, simple and fast way to keep notes directly via terminal.
description: |
  Shellnotes is a note system for linux users, that helps you take your notes from wherever you are,
  whenever you want, using your favourite text editor.
title: shellnotes (note system)
grade: stable
confinement: strict
architectures: [ all ]

apps:
   shellnotes:
       command: shellnotes

parts:
  movies:
    source: .
    plugin: dump
    stage-packages: [git]
    build-packages: [g++, git, apt, wget, curl, python]
     

parts:
  shellnotes:
    source: .
    plugin: dump
    override-pull: |
      snapcraftctl pull
      pwd
      chmod +x ./shellnotes.sh
    override-build: |
      gem install csv -I $SNAPCRAFT_PART_INSTALL
      snapcraftctl build

    
